//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mapEditorRes.rc
//
#define IDR_MAINWINDOW                  102
#define IDD_DLG_ABOUT                   103
#define IDR_TOOLBAR                     106
#define IDD_DLG_ADDTEXTURE              110
#define IDD_DLG_MODIFYTEX               111
#define IDI_EDITOR                      113
#define IDB_ABOUTME                     114
#define IDD_DLG_REGISTER                115
#define IDD_DLG_NEWSCENE                116
#define IDD_DLG_TERRAINATTRIB           118
#define IDD_DLG_CONFIGAPP               119
#define IDC_APP_BRUSH                   121
#define IDC_APP_MOVE                    122
#define IDC_APP_SCALE                   123
#define IDC_APP_ROTATE                  124
#define IDD_DLG_ADDMESHTEMPLATE         125
#define IDD_DLG_ADDMESHACTOR            126
#define IDD_DLG_ROTATE                  127
#define IDD_DLG_STARTUP                 128
#define IDB_STARTUP                     129
#define IDD_DLG_PROGRESS                130
#define IDD_DLG_SETSKYBOX               131
#define IDD_DLG_SETLIGHT                132
#define IDD_DLG_SETFOG                  133
#define IDD_DLG_PLUGINS                 134
#define IDD_DLG_ADDWATERTEMPLATE        135
#define IDD_DLG_SETVECTOR               137
#define IDD_DLG_SELTEXTURE              140
#define IDD_DLG_PREVIEWTEX              141
#define IDD_DLG_TILETEXTURE             142
#define IDD_DLG_SELFILE                 143
#define IDD_DLG_ACTORLIST               145
#define IDD_DLG_ENTITYLIST              145
#define IDD_DLG_ADDGRASS                146
#define IDD_DLG_ADDVEGETATION           146
#define IDD_DLG_MAPINFO                 148
#define IDD_DLG_LIGHTMAP                149
#define IDD_DLG_LIGHTMODE               149
#define IDD_DLG_FOGSTATE                150
#define IDD_DLG_SKYBOX                  151
#define IDB_ACTOR_TYPE                  152
#define IDB_ACTOR_ELEMENT               153
#define IDB_ACTOR_ADDTYPE               154
#define IDD_DLG_EDITORCONFIG            159
#define IDD_DLG_APPLYTEXTURE            160
#define IDD_DLG_EDITSKYBOX              162
#define IDD_DLG_ENTITYNAME              163
#define IDD_DLG_MAKELIGHTMAP            164
#define IDD_DLG_ADDANIMATION            165
#define IDD_DLG_ADDSPRITE               167
#define IDD_DLG_EDITWATER               169
#define IDC_ROTA_AXIS_X                 1000
#define IDC_ROTA_AXIS_Y                 1001
#define IDC_ROTA_AXIS_Z                 1002
#define IDC_MESHA_NAME                  1007
#define IDC_ADT_FILEPATH                1007
#define IDC_EDIT2                       1007
#define IDC_ADDMT_FILENAME              1007
#define IDC_MDT_TEXSCALE                1007
#define IDC_ADT_SELFILE                 1008
#define IDC_ADDWT_TEXLIST               1008
#define IDC_BUTTON2                     1008
#define IDC_MDT_SUBSCALE                1008
#define IDC_EDIT5                       1008
#define IDC_ALIST_SELECTALLTYPE         1008
#define IDC_LMAP_DIFFUSE                1008
#define IDC_LGT_DIFFUSE                 1008
#define IDC_CFG_ADDSKY                  1008
#define IDC_ETLIST_SELECTALLTYPE        1008
#define IDC_MKLGT_DIFFUSE               1008
#define IDC_ADDVEG_SEL1                 1008
#define IDC_WATER_SEL2                  1008
#define IDC_SKY_BACK                    1009
#define IDC_TATT_SIZESCALE              1009
#define IDC_MDT_ADDSCALE                1009
#define IDC_ALIST_SELECTNONETYPE        1009
#define IDC_LMAP_AMBIENT                1009
#define IDC_LGT_AMBIENT                 1009
#define IDC_EDITSKY_LEFT                1009
#define IDC_CFG_DELETESKY               1009
#define IDC_ETLIST_SELECTNONETYPE       1009
#define IDC_ADDVEG_TEXTURE              1009
#define IDC_SKY_SELBACK                 1010
#define IDC_ALIST_INVERTTYPE            1010
#define IDC_ETLIST_INVERTTYPE           1010
#define IDC_ADDVEG_SEL2                 1010
#define IDC_SKY_LEFT                    1011
#define IDC_ADT_PREVIEW                 1011
#define IDC_SKY_SELLEFT                 1012
#define IDC_REG_SERIALCODE              1012
#define IDC_REG_USERNAME                1013
#define IDC_COMBO1                      1013
#define IDC_SKY_RIGHT                   1013
#define IDC_REG_REGCODE                 1014
#define IDC_COMBO2                      1014
#define IDC_SKY_SELRIGHT                1014
#define IDC_SKY_UP                      1015
#define IDC_COMBO3                      1015
#define IDC_SKY_SELUP                   1016
#define IDC_SKY_DOWN                    1017
#define IDC_SKY_SELDOWN                 1018
#define IDC_ADDMT_TEMNAME               1019
#define IDC_ADDMT_SELFILE               1020
#define IDC_ADDMA_POSITION_X            1025
#define IDC_ADDMA_POSITION_Y            1026
#define IDC_ADDMA_POSITION_Z            1027
#define IDC_ADDMA_ROTATION_X            1028
#define IDC_ADDMA_ROTATION_Y            1029
#define IDC_ADDMA_ROTATION_Z            1030
#define IDC_ADDMA_SCALE_X               1031
#define IDC_ADDMA_SCALE_Y               1032
#define IDC_ADDMA_SCALE_Z               1033
#define IDC_ADDMA_TEMLIST               1034
#define IDC_MESHA_TEMLIST               1034
#define IDC_START_TEXTBAR               1035
#define IDC_PBAR_PROGRESS               1036
#define IDC_PBAR_TEXT                   1037
#define IDC_ADT_NAME                    1038
#define IDC_MDT_PREVIEW                 1039
#define IDC_MDT_TEXPATH                 1040
#define IDC_MDT_SELFILE                 1041
#define IDC_MDT_NAME                    1043
#define IDC_EDIT1                       1044
#define IDC_NEWSCENE_NAME               1044
#define IDC_TILE_TEXSCALE               1044
#define IDC_ADDGRASS_NAME               1044
#define IDC_MAPA_NAME                   1044
#define IDC_CFG_MAXHEIGHT               1044
#define IDC_EDITSKY_NAME                1044
#define IDC_APPLYALL_SCALE              1044
#define IDC_ETNAME_NAME                 1044
#define IDC_ADDANIM_MODEL               1044
#define IDC_ADDSPT_NAME                 1044
#define IDC_WATER_SURFACEMAP            1044
#define IDC_BUTTON1                     1045
#define IDC_SETL_LPOS_Y                 1045
#define IDC_SETVEC_Y                    1045
#define IDC_ALIST_SELECTALL             1045
#define IDC_ADDGRASS_TEX                1045
#define IDC_LMAP_POSITION               1045
#define IDC_CFG_WIRECOLOR               1045
#define IDC_ETLIST_SELECTALL            1045
#define IDC_MKLGT_LIGHTDIR              1045
#define IDC_ADDANIM_SEL1                1045
#define IDC_ADDSPT_ADDTEX               1045
#define IDC_WATER_SEL1                  1045
#define IDC_SETVEC_Z                    1046
#define IDC_ALIST_SELECTNONE            1046
#define IDC_LGT_DIRECTION               1046
#define IDC_FOG_SELCOLOR                1046
#define IDC_ETLIST_SELECTNONE           1046
#define IDC_ADDANIM_ANIMATION           1046
#define IDC_ADDSPT_DELTEX               1046
#define IDC_EDIT3                       1047
#define IDC_ALIST_INVERT                1047
#define IDC_EDITSKY_RIGHT               1047
#define IDC_CFG_CAMROTATESPEED          1047
#define IDC_ETLIST_INVERT               1047
#define IDC_ADDANIM_SEL2                1047
#define IDC_ADDSPT_HEIGHT               1047
#define IDC_ADDVEG_WIDTH                1047
#define IDC_WATER_TEXSCALE              1047
#define IDC_BUTTON4                     1048
#define IDC_EDITSKY_TOP                 1048
#define IDC_BUTTON5                     1049
#define IDC_EDITSKY_BOTTOM              1049
#define IDC_EDIT4                       1050
#define IDC_CFG_ETROTATESPEED           1050
#define IDC_ADDSPT_FPS                  1050
#define IDC_ADDVEG_HEIGHT               1050
#define IDC_WATER_DISTORTION            1050
#define IDC_TATT_SIZESCALE_SUB          1051
#define IDC_WATER_FLOWSPEED             1051
#define IDC_TATT_SIZESCALE_ADD          1052
#define IDC_TATT_NAME                   1053
#define IDC_TATT_SIZE                   1054
#define IDC_TATT_ALPHASIZE              1055
#define IDC_TATT_HEIGHTSCALE            1056
#define IDC_TATT_HEIGHTSCALE_SUB        1057
#define IDC_TATT_HEIGHTSCALE_ADD        1058
#define IDC_TATT_MAINSCALE              1059
#define IDC_TATT_MAINSCALE_SUB          1060
#define IDC_TATT_MAINSCALE_ADD          1061
#define IDC_TATT_MAINTEX                1062
#define IDC_TATT_SELTEXFILE             1063
#define IDC_SKY_FRONT                   1064
#define IDC_SKY_SELFRONT                1065
#define IDC_SETL_LPOS_X                 1066
#define IDC_SETL_LCOLOR                 1067
#define IDC_SETL_CHANGECOLOR            1068
#define IDC_PLUGIN_PLGLIST              1069
#define IDC_PLUGIN_DETAIL               1071
#define IDC_ADDWT_SIMPLE                1072
#define IDC_ADDWT_ANIM                  1073
#define IDC_ADDWT_DYNAMIC               1074
#define IDC_ADDWT_NAME                  1076
#define IDC_ADDWT_TEXTURE               1077
#define IDC_ADDWT_SEL2                  1078
#define IDC_ADDWT_SEL1                  1079
#define IDC_SETL_LIGHTPOS               1081
#define IDC_SETVEC_SPINX                1082
#define IDC_SETVEC_SPINY                1083
#define IDC_SETVEC_SPINZ                1084
#define IDC_SETVEC_X                    1085
#define IDC_MESHA_POSITION              1086
#define IDC_MESHA_ROTATION              1087
#define IDC_MESHA_SETSCALE              1088
#define IDC_MESHA_SCALE                 1089
#define IDC_SPIN1                       1110
#define IDC_SPIN2                       1111
#define IDC_CFG_SPIN8                   1112
#define IDC_WATER_SPIN3                 1112
#define IDC_SELTEX_TEXLIST              1113
#define IDC_LIST1                       1114
#define IDC_TILE_TEXTURELIST            1114
#define IDC_SELFILE_LIST                1114
#define IDC_ALIST_OBJLIST               1114
#define IDC_CFG_SKYBOXLIST              1114
#define IDC_ETLIST_OBJLIST              1114
#define IDC_ADDSPT_TEXTURELIST          1114
#define IDC_TILE_PREVIEW                1116
#define IDC_TILE_TEXINDEX               1117
#define IDC_TILE_SPIN1                  1119
#define IDC_ALIST_MESH                  1122
#define IDC_ETLIST_MESH                 1122
#define IDC_ALIST_GRASS                 1123
#define IDC_ADDGRASS_TYPE1              1123
#define IDC_ETLIST_VEGETATION           1123
#define IDC_ALIST_ANIMATION             1124
#define IDC_ADDGRASS_TYPE2              1124
#define IDC_ETLIST_ANIMATION            1124
#define IDC_ALIST_PARTICLE              1125
#define IDC_ETLIST_PARTICLE             1125
#define IDC_ALIST_SOUND                 1126
#define IDC_ETLIST_LIQUID               1126
#define IDC_ALIST_SPIRIT                1127
#define IDC_SELFILE_FOLDER              1127
#define IDC_ETLIST_SPIRIT               1127
#define IDC_MAPA_SIZE                   1128
#define IDC_MAPA_ALPHASIZE              1129
#define IDC_MAPA_TILESIZE               1130
#define IDC_MAPA_UNITLENGTH             1131
#define IDC_MAPA_HEIGHTSCALE            1132
#define IDC_MAPA_ENTITYCOUNT            1133
#define IDC_MAPA_MAPSIZE                1134
#define IDC_MAPA_SPIN1                  1135
#define IDC_MAPA_SPIN2                  1136
#define IDC_LMAP_ENABLELIGHT            1137
#define IDC_LGT_ENABLELIGHT             1137
#define IDC_SPIN3                       1138
#define IDC_FOG_SPIN3                   1138
#define IDC_CFG_SPIN3                   1138
#define IDC_ADDSPT_SPIN3                1138
#define IDC_FOG_ENABLEFOG               1139
#define IDC_FOG_MODE                    1140
#define IDC_SKYBOX_ENABLESKY            1143
#define IDC_SKYBOX_LIST                 1144
#define IDC_SKYBOX_SKYLIST              1144
#define IDC_APPLYALL_MAIN               1147
#define IDC_APPLYALL_DETAIL1            1148
#define IDC_APPLYALL_DETAIL2            1149
#define IDC_APPLYALL_DETAIL3            1150
#define IDC_APPLYALL_DETAIL4            1151
#define IDC_FOG_DENSITY                 1152
#define IDC_FOG_SPIN1                   1153
#define IDC_FOG_SPIN2                   1154
#define IDC_FOG_NEAR                    1155
#define IDC_FOG_FAR                     1156
#define IDC_CFG_CAMMOVESPEED            1157
#define IDC_EDITSKY_FRONT               1158
#define IDC_CFG_CLIPNEAR                1158
#define IDC_EDITSKY_BACK                1159
#define IDC_CFG_CLIPFAR                 1159
#define IDC_CFG_SPIN1                   1160
#define IDC_CFG_SPIN2                   1161
#define IDC_CFG_BACKCOLOR               1162
#define IDC_CFG_SPIN4                   1163
#define IDC_CFG_SPIN5                   1164
#define IDC_APPLYALL_SPIN1              1166
#define IDC_CFG_ETSCALESPEED            1167
#define IDC_CFG_ETMOVESPEED             1168
#define IDC_CFG_SPIN6                   1169
#define IDC_CFG_SPIN7                   1170
#define IDC_PROGRESS1                   1172
#define IDC_MKLGT_PROGRESS1             1172
#define IDC_BUTTON3                     1173
#define IDC_MKLGT_AMBIENT               1173
#define IDC_ADDSPT_SELXML               1173
#define IDC_WATER_POSITION              1173
#define IDC_CHECK1                      1174
#define IDC_MKLGT_TERRAINSHADOW         1174
#define IDC_ADDSPT_BILLBOARDY           1174
#define IDC_WATER_REFLTERRAIN           1174
#define IDC_CHECK2                      1175
#define IDC_MKLGT_MESHSHADOW            1175
#define IDC_WATER_REFLENTITY            1175
#define IDC_ADDANIM_FPS                 1176
#define IDC_ADDANIM_SPIN1               1177
#define IDC_ADDSPT_FROMXML              1179
#define IDC_ADDSPT_USERDEFINE           1180
#define IDC_ADDSPT_XMLPATH              1181
#define IDC_ADDSPT_WIDTH                1182
#define IDC_ADDSPT_SPIN1                1183
#define IDC_ADDSPT_SPIN2                1184
#define IDC_ADDVEG_FROMMESH             1185
#define IDC_ADDVEG_USERDEFINE           1186
#define IDC_ADDVEG_POS1X                1187
#define IDC_ADDVEG_POS1Y                1188
#define IDC_ADDVEG_POS2X                1189
#define IDC_ADDVEG_POS2Y                1190
#define IDC_ADDVEG_MESH                 1191
#define IDC_ADDVEG_POLYCOUNT            1192
#define IDC_WATER_REFLSKY               1195
#define IDC_WATER_REFLECTION            1197
#define IDC_WATER_DISTORTMAP            1198
#define IDC_WATER_SPIN1                 1199
#define IDC_WATER_SPIN2                 1200
#define IDC_WATER_NAME                  1201
#define IDC_WATER_WIDTH                 1203
#define IDC_WATER_HEIGHT                1204
#define IDC_WATER_SPIN5                 1205
#define IDC_WATER_SPIN4                 1206
#define ID_FILE_SAVEAS                  40001
#define IDM_FILE_SAVEAS                 40001
#define ID_FILE_EXIT                    40003
#define IDM_FILE_EXIT                   40003
#define ID_TOOL_SMOOTH                  40004
#define IDM_TOOL_SMOOTH                 40004
#define ID_HELP_ABOUT                   40005
#define IDM_HELP_ABOUT                  40005
#define ID_BUTTON40006                  40006
#define ID_BUTTON40007                  40007
#define ID_BUTTON40008                  40008
#define ID_BUTTON40009                  40009
#define IDM_VIEW_WIREFRAME              40010
#define IDM_VIEW_TEXTURE                40011
#define IDM_VIEW_WIRETEX                40012
#define IDM_VIEW_RESETCAM               40013
#define IDM_TERR_IMPHEIGHT              40014
#define IDM_TER_IMPHEIGHT               40014
#define IDM_MAP_IMPHEIGHT               40014
#define IDM_TERR_EXPHEIGHT              40015
#define IDM_TER_EXPHEIGHT               40015
#define IDM_MAP_EXPHEIGHT               40015
#define IDM_HELP_REGISTER               40016
#define IDM_FILE_NEW                    40017
#define IDM_FILE_OPEN                   40018
#define IDM_FILE_SAVE                   40019
#define IDM_TER_ATTRIBUTE               40020
#define IDM_MAP_ATTRIBUTE               40020
#define IDM_HELP_HELPME                 40021
#define IDM_TOOL_CALCLIGHT              40022
#define IDM_FILE_EXPORT                 40023
#define IDM_FILE_EXPORTENTITY           40023
#define ID_BUTTON40024                  40024
#define ID_BUTTON40025                  40025
#define IDM_EDIT_SELECTALL              40026
#define IDM_EDIT_INVSELECT              40027
#define IDM_EDIT_SELECTNO               40028
#define IDM_EDIT_HIDESEL                40029
#define IDM_EDIT_HIDENOSEL              40030
#define IDM_EDIT_HIDENOHIDE             40030
#define IDM_EDIT_SHOWALL                40032
#define ID_BUTTON40033                  40033
#define ID_BUTTON40034                  40034
#define IDM_TOOL_PLUGINS                40035
#define IDM_FILE_RESET                  40036
#define IDM_VIEW_COLLISIONCAM           40037
#define IDM_VIEW_CAM_EDIT               40038
#define IDM_VIEW_CAM_RAMBLE             40039
#define IDM_MAP_CALCLIGHT               40040
#define IDM_MAP_LIGHTMAP                40040
#define ID_BUTTON40041                  40041
#define ID_BUTTON40042                  40042
#define ID_BUTTON40043                  40043
#define ID_BUTTON40044                  40044
#define IDM_MAP_FOGSTATE                40045
#define IDM_MAP_SKYBOX                  40046
#define IDM_MAP_WATER                   40047
#define IDM_EDIT_DELETE                 40048
#define ID_BUTTON40049                  40049
#define IDM_MAP_EXPLIGHTMAP             40050
#define IDM_MAP_IMPLIGHTMAP             40051
#define IDM_TOOL_OPTIONS                40052
#define IDM_FILE_IMPORTENTITY           40053
#define IDM_VIEW_SOLID                  40054
#define IDM_MAP_LIGHT                   40055
#define ID_BUTTON40056                  40056
#define IDM_EDIT_HIDEALL                40058

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         40059
#define _APS_NEXT_CONTROL_VALUE         1207
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
